### PR TITLE
Updated to the Rust 2018 edition

### PR DESCRIPTION
**Pull request by XVilka**
Updated to the 2018 edition, also updated all dependencies. Note, I didn't update the style, just did minimal changes to make it work in the modern environment. If/when this merged, I might check for some code modernization possibilities.

P.S. I think it is better to squash these commits into one before merging.

### CODE REVIEW

**Comment by XVilka** [comment]
Note, I updated the Travis CI file now, it now builds, you can see the build logs and results here: https://travis-ci.org/XVilka/roper2/builds/565836377
So you can also enable Travis and add the badge in README (as well as README itself), so you can close https://github.com/oblivia-simplex/roper2/issues/1.

I had to disable the `cargo test` for now, since there are missing files for the `cargo test` target: https://github.com/oblivia-simplex/roper2/issues/3

**Comment by XVilka** [comment]
@oblivia-simplex so, what do you think about this change?

**Comment by XVilka** [comment]
Still green - see https://travis-ci.org/XVilka/roper2/builds/606989763:

image

**Comment by XVilka** [comment]
Updated dependencies one more time, applied some clippy and style fixes, and reformatted the code with `cargo +stable fmt --all`

Travis is still green after:
image

**Comment by XVilka** [comment]
Sometimes `uc.mem_read(addr. &mut bytecode).is_ok()` returns Ok but fails to read anything, thus `bytecode` length is 0, so I just ignore these cases now - see the latest commit.

**Comment by oblivia-simplex** [comment]
Hey, thanks for all of your hacking on this project! I haven't looked at it in a while, and am just getting back to it now. I appreciate all the work you've put into this.

**Pull request merged**
